// src/app/components/edit-todo/edit-todo.component.ts
import { Component, OnInit } from '@angular/core';
import { Router,ActivatedRoute } from '@angular/router';
import { TodoService } from 'src/app/todo.service';


@Component({
  selector: 'app-edit-todo',
  templateUrl: './edit-todo.component.html',
  styleUrls: ['./edit-todo.component.css']
})
export class EditTodoComponent implements OnInit {
  currentTodo: any = {id:0, title: '', description:''}

  constructor(
    private todoService: TodoService,
    private router: Router,
    private route:ActivatedRoute
    ) { }

  ngOnInit(): void {

    this.route.paramMap.subscribe((params)=>{
      if(params.has('id') && params.has('title') && params.has('description')){
        const todoId = params.get('id');
        const title = params.get('title');
        const description = params.get('description');
        this.currentTodo = {id:todoId, title, description}
      }else{
        alert("Hey Yo!! are not authorized to navigate here!!")
      }
    })
  }
  
  updateTodo():void{
    this.todoService.updateTodo(this.currentTodo);
    this.router.navigate(['/'])
  }

  cancelEdit(): void{
    this.router.navigate(['/'])
  }

}

<div class="edit-todo-container">
    <h2>Edit Todo</h2>
    <div class="edit-todo-form">
        <label for="">Title</label>
        <input type="text" [(ngModel)]="currentTodo.title">
        <label for="">Description</label>
        <textarea [(ngModel)] = "currentTodo.description"></textarea>
        <div class="edit-todo-buttons">
            <button (click)="updateTodo()" class="save">Update</button>
            <button (click)="cancelEdit()" class="cancel">Cancel</button>
        </div>
    </div>
</div>

// react/src/components/EditTodo.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";

const EditTodo = ({currentTodo, onUpdate, onCancel}) => {

    const navigate = useNavigate();
    const [editedTodo, setEditedTodo] = useState(currentTodo || {title:'', description:''});

    // alert(JSON.stringify(editedTodo))

    const handleSave = () => {
        onUpdate(editedTodo);
        navigate('/');
    }
    const handleCancel = () => {
        onCancel();
        navigate('/');
    }

    return (
        <div className="edit-todo-container">
            <h2>Edit Todo</h2>
            <form onSubmit={handleSave}>
                <div className="edit-todo-form">
                    <label>Title:</label>
                    <input
                        required
                        type="text"
                        value={editedTodo.title}
                        onChange={(e) => setEditedTodo({ ...editedTodo, title: e.target.value })}
                    />
                    <label>Description:</label>
                    <textarea
                        required
                        value={editedTodo.description}
                        onChange={(e) => setEditedTodo({ ...editedTodo, description: e.target.value })}
                    />
                    <div className="edit-todo-buttons">
                        <button type="submit" className="save">Save</button>
                        <button className="cancel" onClick={handleCancel}>Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    );
}
export default EditTodo;
